AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/delayed_job'
    - 'app/views/posts/*.haml'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
Documentation:
  Enabled: false
